# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
# ↓ --------------------------

title: June's Blog

tagline: 반갑습니다.<br/>질문이나 요청 사항은<br/>댓글이나<br/>메일로 부탁드립니다.

description: developer, kotlin, java, c#, algorithm

# Fill in the protocol & hostname without a trailing slash.
url: "https://ijung.github.io"

github:
  username: ijung

twitter:
  username:

social:
  name: June
  email: spd1335@gmail.com
  fediverse_handle:
  links:
    - https://github.com/ijung

# Site Verification Settings
webmaster_verifications:
  google: LohgyTrhhUzf1b5frYPbIZtOijNJJ4-5svugDR2gcVQ
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-8ZTXDS4Q4J
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode: dark # [light | dark]

# The CDN endpoint for media resources.
cdn: ""

# The avatar on sidebar, supports local or CORS resources.
avatar: assets/img/avatar/somi.jpg

# The URL of the site-wide social preview image.
social_preview_image:

# Global switch for TOC in posts.
toc: true

actions:
  edit_post:
    enabled: false
    url: ""
    static_url: false

comments:
  provider: utterances
  disqus:
    shortname:
  utterances:
    repo: ijung/ijung.github.io
    issue_term: pathname
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets, optional.
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# The base URL of your site.
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
